### ISSUE TITLE
Missing ./lib/karma-webpack

### ISSUE THREAD

**Issue by mortenda** [webpack/karma-webpack#198]
Great work on getting the 2.0.0 out :)

It seems that some files are missing from the package though.

Getting this when running tests:
```
11 01 2017 23:05:12.028:ERROR [plugin]: Error during loading "C:\Projects\my-project\node_modules/karma-webpack" plugin:
  Cannot find module './lib/karma-webpack'
11 01 2017 23:05:12.040:ERROR [preprocess]: Can not load "webpack", it is not registered!
  Perhaps you are missing some plugin?
```

And looking at node_modules/karma-webpack it is missing a lib folder as it is exported in index.js.

Tried removing and reinstalling karma-webpack but same thing happens.

**Comment by d3viant0ne** [comment]
Pick up 2.0.1
